# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['webex_gui.py'],
    pathex=[],
    binaries=[],
    datas=[('Webex Archive', 'Webex Archive')],
    hiddenimports=[
        '_socket',
        'socket',
        'select',
        'selectors',
        '_ssl',
        'ssl',
        'multiprocessing',
        'multiprocessing.pool',
        'multiprocessing.reduction',
        'multiprocessing.synchronize',
        'multiprocessing.spawn',
        'multiprocessing.popen_spawn_win32',
        'multiprocessing.context',
        'multiprocessing.util',
        'queue',
        'threading',
        'subprocess',
        'importlib',
        'importlib.util',
        'configparser',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.sip',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Webex Archive Manager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Webex Archive Manager',
)
